language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -f d spec/
deploy:
  provider: heroku
  api_key:
    secure: F8MheYAblJmxl9kqTjtZWpR1y6OmjHx7nl9c+ShQzzD6X5EZLsKNyLXo0ysqzq1Hv/jifUMx9bl3lJ53xPBgKpRJV0OZ4jATB5836TNCU+hLliULvivKM08XMkZ/IDW+S611J55I4bAyvvfdq/neHeIH2zv+w84NY3V+AlfBNeo=
  app: aktivator-plusplus
  on:
    repo: a-plus-plus/aktivator
