language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -f d spec/
deploy:
  provider: heroku
  api_key:
    secure: QYdJsI9wMWf3Vu2HP+sdKKQPP1rCBaxatdp207OEc0OfbSxo/KVWUTnki6B10xWZCqHa5dJQx7UJNg2G4a7NsDexMCw3YWiK5gLH499fpGyq1zYdJL7cGp3lfQZTVbHF/5KgpECAGo9r6NpA06oJ16rvDhEtE1f3MaWhj3v4LBU=
  app: aktivator-plusplus
  on:
    repo: a-plus-plus/aktivator
