require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.


describe OptionsController do
  pending "TODO, evaluate if options controller and tests are necessary"
=begin
  login_user
  # This should return the minimal set of attributes required to create a valid
  # Option. As you add validations to Option, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:option).attributes.symbolize_keys }  

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  before :each do
    request.env["HTTP_ACCEPT"] = 'application/json' 
  end

  describe "GET index" do
    it "assigns all options as @options" do
      option = Option.create! valid_attributes
      get :index, {}, valid_session
      assigns(:options).should eq([option])
    end
  end

  describe "GET show" do
    it "assigns the requested option as @option" do
      option = Option.create! valid_attributes
      get :show, {:id => option.to_param}, valid_session
      assigns(:option).should eq(option)
    end
  end

  
  describe "POST create" do
    describe "with valid params" do
      it "creates a new Option" do
        expect {
          post :create, {:option => valid_attributes}, valid_session
        }.to change(Option, :count).by(1)
      end

      it "assigns a newly created option as @option" do
        post :create, {:option => valid_attributes}, valid_session
        assigns(:option).should be_a(Option)
        assigns(:option).should be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved option as @option" do
        # Trigger the behavior that occurs when invalid params are submitted
        Option.any_instance.stub(:save).and_return(false)
        post :create, {:option => { "question" => "invalid value" }}, valid_session
        assigns(:option).should be_a_new(Option)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested option" do
        option = Option.create! valid_attributes
        # Assuming there are no other options in the database, this
        # specifies that the Option created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Option.any_instance.should_receive(:update).with({ "question_id" => "1" })
        put :update, {:id => option.to_param, :option => { "question_id" => "1" }}, valid_session
      end

      it "assigns the requested option as @option" do
        option = Option.create! valid_attributes
        put :update, {:id => option.to_param, :option => valid_attributes}, valid_session
        assigns(:option).should eq(option)
      end
    end

    describe "with invalid params" do
      it "assigns the option as @option" do
        option = Option.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Option.any_instance.stub(:save).and_return(false)
        put :update, {:id => option.to_param, :option => { "question" => "invalid value" }}, valid_session
        assigns(:option).should eq(option)
      end

     end
  end

  describe "DELETE destroy" do
    it "destroys the requested option" do
      option = Option.create! valid_attributes
      expect {
        delete :destroy, {:id => option.to_param}, valid_session
      }.to change(Option, :count).by(-1)
    end
  end
=end

end

